package lol.mifan.myblog.model;

// Generated 2017-4-16 20:16:16 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "myblog")
public class Tag implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean deleted;
	private Set<Article> articles = new HashSet<Article>(0);

	public Tag() {
	}

	public Tag(boolean deleted) {
		this.deleted = deleted;
	}

	public Tag(String name, boolean deleted, Set<Article> articles) {
		this.name = name;
		this.deleted = deleted;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "articletag", catalog = "myblog", joinColumns = { @JoinColumn(name = "tag_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "article_id", nullable = false, updatable = false) })
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
